version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "${HOST_PORT}:8000"
    depends_on:
      - migrate
      - redis
    env_file:
      - .env

  migrate:
    build: .
    command: [ "sh", "-c", "python manage.py migrate" ]
    volumes:
      - .:/app
    env_file:
      - .env

  redis:
    image: redis:latest
    command: redis-server --requirepass  ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    env_file:
      - .env

volumes:
  redis_data: